# Site settings
author: Sophia White
title: Teacher to Software Engineer
header-img: img/home-bg.png
email: sophia.g.white@outlook.com
copyright_name: Sophia White
description: > # this means to ignore newlines until "baseurl:"
  My Career Switch at 26
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SophiaGrace16

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
